<?php

$f = fopen('../person.json', 'w');
$files = scandir('.');


$map = [
"aleksandr anokhon" => ["name" => "Александр Анохин",
    "dep" =>"RU Office Support","position" =>"Руководитель Отдела поддержки офисов",
        "priority" => 3],
"aleksandr novodvorskiy" => ["name" => "Александр Новодворский",
    "dep" =>"RU Investment Department","position" =>"Руководитель",
        "priority" => 2],
"alexander chebotarev" => ["name" => "Александр Чеботарев",
    "dep" =>"RU Client-Side Development","position" =>"Руководитель Отдела разработки клиентской стороны сайтов",
        "priority" => 3],
"alexander lisachenko" => ["name" => "Александр Лисаченко",
    "dep" =>"RU Software Architecture","position" =>"Руководитель Отдела проектирования ПО",
        "priority" => 3],
"alexander razuvaev" => ["name" => "Александр Разуваев",
    "dep" =>"RU Market Research","position" =>"Руководитель отдела аналитики",
        "priority" => 3],
"alexander tarassenko" => ["name" => "Александр Тарассенко",
    "dep" =>"RU Trading Platform Integration","position" =>"Руководитель Отдела интеграции торговых платформ",
        "priority" => 3],
"alexandr gorodniy" => ["name" => "Александр Городный",
    "dep" =>"RU Projects and Support Department","position" =>"Руководитель",
        "priority" => 3],
"alexey baranov" => ["name" => "Алексей Баранов",
    "dep" =>"RU Software Development Department","position" =>"Руководитель департамента разработок ПО",
        "priority" => 2],
"alexey budnikov" => ["name" => "Алексей Будников",
    "dep" =>"RU Assistant to the CEO","position" =>"Помощник СЕО",
        "priority" => 3],
"alexey zabatov" => ["name" => "Алексей Забатов",
    "dep" =>"RU Financial Services Development","position" =>"и.о. руководителя Отдела разработки финансовых сервисов",
        "priority" => 3],
"alla kotova" => ["name" => "Алла Котова",
    "dep" =>"RU Sales Department","position" =>"Руководитель Департамента продаж",
        "priority" => 2],
"alla zvereva" => ["name" => "Алла Зверева",
    "dep" =>"RU Project Indonesia","position" =>"Руководитель Проекта Индонезия",
        "priority" => 2],
"andrey dashin" => ["name" => "Андрей Дашин",
    "dep" =>"RU Chairman of the Board of Directors","position" =>"Председатель Совета директоров",
        "priority" => 1],
"andrey lisitsyn" => ["name" => "Андрей Лисицын",
    "dep" =>"RU Chief Srategy Officer","position" =>"Директор по стратегическим вопросам",
        "priority" => 1],
"andrey loboda" => ["name" => "Андрей Лобода",
    "dep" =>"RU PR","position" =>"руководитель Отдела PR",
        "priority" => 3],
"andrey salnikov" => ["name" => "Андрей Сальников",
    "dep" =>"RU UNIX and Network Solutions","position" =>"Руководитель IT-Департамента",
        "priority" => 2],
"andrey tarasov" => ["name" => "Андрей Тарасов",
    "dep" =>"RU Managing Director","position" =>"Исполнительный директор",
        "priority" => 1],
"anna tokareva" => ["name" => "Анна Токарева",
    "dep" =>"RU HR / Employee Incentives","position" =>"Руководитель Отдела кадров и мотивационной политики",
        "priority" => 3],
"anna trubetskaya" => ["name" => "Анна Трубецкая",
    "dep" =>"RU Project Nigeria","position" =>"Руководитель Проекта Нигерия",
        "priority" => 2],
"anton borisov" => ["name" => "Антон Борисов",
    "dep" =>"RU Investment Products","position" =>"Руководитель Отдела развития инвестиционных продуктов",
        "priority" => 3],
"boris shilov" => ["name" => "Борис Шилов",
    "dep" =>"RU Chief Executive Officer (CEO)","position" =>"Генеральный директор (CEO)",
        "priority" => 1],
"denis andreev" => ["name" => "Денис Андреев",
    "dep" =>"RU Back-office","position" =>"Руководитель Отдела бэк–офис Департамента расчетов и платежей.",
        "priority" => 3],
"dmitry ulybin" => ["name" => "Дмитрий Улыбин",
    "dep" =>"RU Russian Legal Entities Division","position" =>"и.о. руководителя Отдела по работе с российскими юридическими лицами",
        "priority" => 3],
"elizaveta skogoreva" => ["name" => "Елизавета Скогорева",
    "dep" =>"RU Education (Alpari Trading School)","position" =>"Руководитель Отдела обучения",
        "priority" => 3],
"evgeniya kit" => ["name" => "Евгения Кит",
    "dep" =>"RU Department of settlements and payments","position" =>"Руководитель Департамента расчетов и платежей",
        "priority" => 2],
"gulnara nazirova" => ["name" => "Гульнара Назирова",
    "dep" =>"RU Department of Accounting and Reporting","position" =>"Руководитель Департамента учета и отчетности",
        "priority" => 3],
"igor kuzin" => ["name" => "Игорь Кузин",
    "dep" =>"RU Chief Finance Officer","position" =>"Финансовый директор",
        "priority" => 1],
"ildar giniyatov" => ["name" => "Ильдар Гиниятов",
    "dep" =>"RU Advertising","position" =>"Руководитель отдела рекламы",
        "priority" => 3],
"alexey kovrizhnyh" => ["name" => "Алексей Коврижных",
    "dep" =>"RU Office-Administration","position" =>"Руководитель",
        "priority" => 2],
"ivan koshkarev" => ["name" => "Иван Кошкарев",
    "dep" =>"RU Projects","position" =>"Руководитель",
        "priority" => 2],
"ivan kosilov" => ["name" => "Иван Косилов",
    "dep" =>"RU Investment Support","position" =>"Руководитель отдела консультирования ПАММ",
        "priority" => 3],
"konstantin shvydkiy" => ["name" => "Константин Швыдкий",
    "dep" =>"RU Investment Web development","position" =>"руководителя Отдела разработок",
        "priority" => 3],
"konstantin smirnov" => ["name" => "Константин Смирнов",
    "dep" =>"RU C++ Development","position" =>"Руководитель отдела Си- разработок",
        "priority" => 3],
"lev sologubov" => ["name" => "Лев Сологубов",
    "dep" =>"RU BAC&PS Technical Support Team","position" =>"Руководитель отдела технического обеспечения",
        "priority" => 3],
"lyubov volkova" => ["name" => "Любовь Волкова",
    "dep" =>"RU Legal Support of International Business Development","position" =>"Руководитель Отдела юридической поддержки международного",
        "priority" => 3],
"matvey noyachenko" => ["name" => "Матвей Нояченко",
    "dep" =>"RU Department of Data Protection","position" =>"Руководитель департамента информационной безопасности",
        "priority" => 2],
"mihail seliverstov" => ["name" => "Михаил Селиверстов",
    "dep" =>"RU Sales","position" =>"Руководитель продаж",
        "priority" => 2],
"mikhail zhulin" => ["name" => "Михаил Жулин",
    "dep" =>"RU Marketing Research","position" =>"Руководитель Отдела маркетинговых исследований",
        "priority" => 3],
"natalya ideeva" => ["name" => "Наталья Индеева",
    "dep" =>"RU Content Development and Localization","position" =>"Руководитель отдела",
        "priority" => 3],
"nikolay andrianov" => ["name" => "Николай Андриянов",
    "dep" =>"RU BAC&PS Analytical Team","position" =>"Руководитель Департамента внутреннего контроля",
        "priority" => 2],
"nikolay mantashyan" => ["name" => "Николая Манташьян",
    "dep" =>"RU Investment DB development","position" =>"Руководитель",
        "priority" => 3],
"pavel dobryakov" => ["name" => "Павел Добряков",
    "dep" =>"RU UNIX and Network Solutions","position" =>"Руководитель Отдела UNIX и сетевых решений",
        "priority" => 2],
"roman rozhencov" => ["name" => "Роман Роженцов",
    "dep" =>"RU Partnership Programs","position" =>"Руководитель",
        "priority" => 3],
"sergey belchikov" => ["name" => "Сергей Бельчиков",
    "dep" =>"RU Client Support","position" =>"Руководитель",
        "priority" => 2],
"sergey maryin" => ["name" => "Сергей Марьин",
    "dep" =>"RU BAC&PS Information Security Team","position" =>"Руководитель отдела информационной безопасности",
        "priority" => 3],
"sergey maslennikov" => ["name" => "Сергей Масленников",
    "dep" =>"RU Dealing Department","position" =>"Руководитель Департамента Дилинга",
        "priority" => 2],
"sergey protsenko" => ["name" => "Андрей Проценко",
    "dep" =>"RU Chief Dealing Officer","position" =>"Директор по развитию и поддержке дилинга",
        "priority" => 1],
"sergey semenov" => ["name" => "Сергей Семенов",
    "dep" =>"RU Alpari Trading School","position" =>"Руководитель",
        "priority" => 2],
"sergey voycehovsky" => ["name" => "Сергей Войцеховский",
    "dep" =>"RU Dealing Trading Team","position" =>"Руководитель Отдела трейдинга",
        "priority" => 3],
"sergey vyazmin" => ["name" => "Сергей Вязьмин",
    "dep" =>"RU Chief of International Development","position" =>"Директор по международному развитию.",
        "priority" => 1],
"slava abyzov" => ["name" => "Слава Абызов",
    "dep" =>"RU Supervisory Board","position" =>"Член совета директоров",
        "priority" => 1],
"stanislav plyuschev" => ["name" => "Станислав Плющев",
    "dep" =>"RU Dealing Trade Support Team","position" =>"Руководитель Отдела Trade Support",
        "priority" => 3],
"tatyana suvorova" => ["name" => "Татьяна Суворова",
    "dep" =>"RU Remote Offices Department","position" =>"Руководитель",
        "priority" => 2],
"tatyana vusataya" => ["name" => "Татьяна Вусатая",
    "dep" =>"RU Accounting in Russian companies","position" =>"Руководитель Отдела учета и отчетности российских юр.лиц",
        "priority" => 3],
"vasiliy kolesnik" => ["name" => "Василий Колесник",
    "dep" =>"RU Chief Technology Officer","position" =>"Chief Technology Officer (CTO) /Руководитель департамента",
        "priority" => 1],
"vasiliy kostjukhin" => ["name" => "Василий Костюхин",
    "dep" =>"RU BAC&PS Organizational Team","position" =>"Руководитель",
        "priority" => 2],
"vitaliy leonov" => ["name" => "Виталий Леонов",
    "dep" =>"RU Dealing Software Department","position" =>"Руководитель Департамента развития и поддержки дилинга",
        "priority" => 2],
"vladimir shatkovsky" => ["name" => "Владимир Шатковский",
    "dep" =>"RU Dealing Services Development","position" =>"Руководитель Отдела разработки сервисов дилинга",
        "priority" => 3],
"vladislav kovalchuk" => ["name" => "Владислав Ковальчук",
    "dep" =>"RU Chief Marketing Officer (CMO)","position" =>"Директор по маркетингу",
        "priority" => 1],
"yuri razmazin" => ["name" => "Юрий Размазин",
    "dep" =>"RU Regional Network Development","position" =>"Руководитель Отдела развития региональной сети",
        "priority" => 3],
"zinnur kafiyatullin" => ["name" => "Зиннур Кафиятуллин",
    "dep" =>"RU Cash Processing Office","position" =>"Руководитель Отдела кассовых операций",
        "priority" => 3]
];

fwrite($f, "[");

foreach ($files as $key => $file) {
    if ($file == '.' || $file == '..' || $file == '1.php' || $file == 'person.json') {
        continue;
    }

    $token = str_replace('.png', '', $file);
    $mapped = $map[$token];

    $str = '';
    $str .= '{' . "\n";
    $str .= '    "name": "' . $mapped['name'] . '",' . "\n";
    $str .= '    "dep": "' . $mapped['dep'] . '",' . "\n";
    $str .= '    "priority": "' . $mapped['priority'] . '",' . "\n";
    $str .= '    "position": "' . $mapped['position'] . '",' . "\n";

    $str .= '    "image": "data:image/png;base64,' . base64_encode(file_get_contents($file)) . '"' . "\n";
    $str .= '}';

    if (($key + 1) != count($files)) {
        $str .= ',';
    }
    $str .= "\n";

    fwrite($f, $str);
}

fwrite($f, "]");
fclose($f);
